apiVersion: v1
kind: Pod
metadata:
 name: fresco-nginx-pod
spec:
  containers:
   - name: fresco-nginx-container
     image: nginx
     volumeMounts:
       - name: test
         mountPath: /etc/test
       - name: html
         mountPath: /usr/share/nginx/html
     env:
      - name: SERVER_URL
        valueFrom:
           configMapKeyRef:
              name: fresco-config
              key: SERVER_URL
  volumes:
   - name: test
     secret:
       secretName: fresco-secret
   - name: html
     persistentVolumeClaim:
       claimName: fresco-pvc
