apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: fresco-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: fresco-pv
  storageClassName: manual
