kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: emp-role
 namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "create" , "list", "delete"]
    
